#Page de garde
App_homepage:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }
services:
    path: /services/
    defaults: { _controller: 'App\Controller\DefaultController::services' }
aPropos:
    path: /aPropos/
    defaults: { _controller: 'App\Controller\DefaultController::apropos' }
nousContacter:
    path: /nousContacter
    defaults: { _controller: 'App\Controller\DefaultController::nousContacter' }

#login et logout
login:
    path: /connexion/
    defaults: { _controller: 'App\Controller\UserController::login'}
logout:
    path: /deconnexion/
